spring:
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/skill?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: root
      type: com.alibaba.druid.pool.DruidDataSource
    freemarker:
      suffix: .html
      cache: false
      template-loader-path: classpath:/templates

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo3.Pojo

